export const USER_DATA_TO_SEND = [
    "id",
    "firstName",
    "lastName",
    "gender",
    "dob",
    "ethnicity",
    "email",
    "documentUrl",
    "state",
    "city",
    "street",
    "insuranceId",
    "memberId",
    "insuranceProvider",
    "isAdmin",
];
export const VACCINE_DATA_TO_SEND = [
    "id",
    "serviceName",
    "serviceLocation",
    "startDate",
    "endDate",
    "numberOfDoses",
    "gender",
    "age",
    "ethnicity",
];
export const APPOINTMENT_DATA_TO_SEND = [
    "id",
    "patientId",
    "siteLocation",
    "serviceType",
    "appointmentDate",
    "appointmentStatus",
];
